#端口
server.port: 8080

#Spring和数据库配置
spring:
  main:
    banner-mode: off   # 关闭SpringBoot启动图标(banner)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qc?serverTimezone=UTC
    username: root
    password: 123456
#  mybatis:
#    logging:
#      level:
#        com.woniuxy.hrp.mapper: debug
#  mapper-locations: classpath:mapper/mapper.WalletMapper

#mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: off   # 关闭mybatisplus启动图标
